# Generated by Django 5.0.7 on 2024-07-10 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=1000)),
                ('Year', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=1000)),
                ('Rating', models.CharField(max_length=1000)),
                ('One_Line', models.CharField(max_length=100000)),
                ('Stars', models.CharField(max_length=100000)),
                ('Votes', models.CharField(max_length=100000)),
                ('Run_Time', models.CharField(max_length=100000)),
                ('Gross', models.CharField(max_length=100000)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
